<?php

declare(strict_types=1);

namespace ContractTests\Tests;

use ContractTests\CallsContractTestCase;

/**
 * Smoke test to validate the entire contract testing flow.
 *
 * This test verifies:
 * 1. Index was generated by bootstrap.php
 * 2. calls.json was loaded successfully
 * 3. Basic query functionality works
 * 4. A known symbol exists in the index
 *
 * Code reference: kloc-reference-project-php/src/Repository/OrderRepository.php
 *   Line 26: public function save(Order $order): Order
 *
 * Expected: A value entry exists with symbol containing 'OrderRepository#save().($order)'
 */
class SmokeTest extends CallsContractTestCase
{
    public function testIndexWasGenerated(): void
    {
        $this->assertFileExists(CALLS_JSON_PATH, 'calls.json should be generated by bootstrap');
    }

    public function testCallsDataLoaded(): void
    {
        $this->assertNotNull(self::$calls, 'CallsData should be loaded');
        $this->assertGreaterThan(0, self::$calls->valueCount(), 'Should have values');
        $this->assertGreaterThan(0, self::$calls->callCount(), 'Should have calls');
    }

    public function testOrderRepositorySaveParameterExists(): void
    {
        // Query for the $order parameter in OrderRepository::save()
        $values = $this->values()
            ->kind('parameter')
            ->symbolContains('OrderRepository#save().($order)')
            ->all();

        $this->assertNotEmpty(
            $values,
            'Should find value entry for $order parameter in OrderRepository::save(). ' .
            'Reference: src/Repository/OrderRepository.php:26'
        );

        // Verify it has expected properties
        $orderParam = $values[0];
        $this->assertEquals('parameter', $orderParam['kind']);
        $this->assertStringContainsString('($order)', $orderParam['symbol']);
        $this->assertNotNull($orderParam['type'] ?? null, 'Parameter should have type');
        $this->assertStringContainsString('Order', $orderParam['type']);
    }

    public function testVersionIsPresent(): void
    {
        $version = self::$calls->version();
        $this->assertNotEmpty($version, 'Version should be present');
        $this->assertMatchesRegularExpression('/^\d+\.\d+/', $version, 'Version should be semver-like');
    }

    public function testValueQueryFiltersWork(): void
    {
        // Test kind filter
        $parameters = $this->values()->kind('parameter')->all();
        $this->assertNotEmpty($parameters, 'Should find parameters');

        foreach ($parameters as $param) {
            $this->assertEquals('parameter', $param['kind']);
        }
    }

    public function testCallQueryFiltersWork(): void
    {
        // Test kind filter
        $methods = $this->calls()->kind('method')->all();
        $this->assertNotEmpty($methods, 'Should find method calls');

        foreach ($methods as $method) {
            $this->assertEquals('method', $method['kind']);
        }
    }
}
