//! Classmap loading from Composer's autoload_classmap.php.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use anyhow::Result;

use super::php_array_parser;

/// Load the Composer classmap from `vendor/composer/autoload_classmap.php`.
///
/// Returns a map from fully qualified class name (e.g., `App\Models\User`)
/// to absolute file path.
///
/// If the classmap file does not exist, returns an empty map.
pub fn load_classmap(vendor_dir: &Path, base_dir: &Path) -> Result<HashMap<String, PathBuf>> {
    let classmap_path = vendor_dir.join("composer/autoload_classmap.php");

    if !classmap_path.exists() {
        return Ok(HashMap::new());
    }

    let content = std::fs::read_to_string(&classmap_path)?;
    let entries = php_array_parser::extract_flat_map(&content, base_dir, vendor_dir);

    let mut map = HashMap::with_capacity(entries.len());
    for (class_name, path) in entries {
        map.insert(class_name, path);
    }

    Ok(map)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn setup_classmap(dir: &TempDir) -> (PathBuf, PathBuf) {
        let root = dir.path().to_path_buf();
        let vendor = root.join("vendor");
        let composer_dir = vendor.join("composer");
        fs::create_dir_all(&composer_dir).unwrap();

        let classmap_content = format!(
            r#"<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'App\\Models\\User' => $baseDir . '/src/Models/User.php',
    'App\\Models\\Post' => $baseDir . '/src/Models/Post.php',
    'Psr\\Log\\LoggerInterface' => $vendorDir . '/psr/log/src/LoggerInterface.php',
);
"#
        );
        fs::write(composer_dir.join("autoload_classmap.php"), classmap_content).unwrap();

        // Create the referenced files
        fs::create_dir_all(root.join("src/Models")).unwrap();
        fs::write(root.join("src/Models/User.php"), "<?php").unwrap();
        fs::write(root.join("src/Models/Post.php"), "<?php").unwrap();
        fs::create_dir_all(vendor.join("psr/log/src")).unwrap();
        fs::write(
            vendor.join("psr/log/src/LoggerInterface.php"),
            "<?php",
        )
        .unwrap();

        (root, vendor)
    }

    #[test]
    fn test_load_classmap() {
        let dir = tempfile::tempdir().unwrap();
        let (root, vendor) = setup_classmap(&dir);
        let map = load_classmap(&vendor, &root).unwrap();

        assert_eq!(map.len(), 3);
        assert!(map.contains_key("App\\Models\\User"));
        assert!(map.contains_key("App\\Models\\Post"));
        assert!(map.contains_key("Psr\\Log\\LoggerInterface"));

        assert_eq!(
            map["App\\Models\\User"],
            root.join("src/Models/User.php")
        );
    }

    #[test]
    fn test_load_classmap_missing_file() {
        let dir = tempfile::tempdir().unwrap();
        let vendor = dir.path().join("vendor");
        let map = load_classmap(&vendor, dir.path()).unwrap();
        assert!(map.is_empty());
    }
}
